package com.fyp.HostelMate.entity;

import com.fyp.HostelMate.entity.enums.PaymentMethod;
import com.fyp.HostelMate.entity.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "payments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Payment {

    @Id
    @GeneratedValue
    @Column(name = "payment_id")
    private UUID paymentId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admission_id", nullable = false)
    private Admission admission;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    private Student student;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hostel_id", nullable = false)
    private Hostel hostel;

    @Column(name = "amount", nullable = false)
    private Double amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false)
    private PaymentMethod paymentMethod;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false)
    private PaymentStatus paymentStatus = PaymentStatus.PENDING;

    /** Month/year this payment covers, e.g. 2025-05-01 = May 2025 */
    @Column(name = "payment_for_month", nullable = false)
    private LocalDate paymentForMonth;

    /** Khalti transaction token or null for cash */
    @Column(name = "transaction_token")
    private String transactionToken;

    /** Khalti's verified transaction ID */
    @Column(name = "khalti_transaction_id")
    private String khaltiTransactionId;

    /** Invoice number for cash payments, generated by hostel */
    @Column(name = "invoice_number")
    private String invoiceNumber;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @Column(name = "paid_at")
    private Instant paidAt;
}
